apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq

---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-creds
spec:
  tags:
    - management # available tags are 'management', 'policymaker', 'monitoring' and 'administrator'
    - policymaker
    - monitoring
    - administrator
  rabbitmqClusterReference:
    name: rabbitmq # rabbitmqCluster must exist in the same namespace as this resource
  importCredentialsSecret:
    name: rabbitmq-creds

---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: user-permission
spec:
  vhost: "/"
  user: "test" # name corresponds to the username we provided in "test-user-credentials" secret
  permissions:
    write: ".*"
    configure: ""
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
